/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DesignersRouteImport } from './routes/designers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShadeIndexRouteImport } from './routes/shade/index'
import { Route as ClinicsIdRouteImport } from './routes/clinics/$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersRoute = DesignersRouteImport.update({
  id: '/designers',
  path: '/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadeIndexRoute = ShadeIndexRouteImport.update({
  id: '/shade/',
  path: '/shade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIdRoute = ClinicsIdRouteImport.update({
  id: '/clinics/$id',
  path: '/clinics/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/designers': typeof DesignersRoute
  '/equipment': typeof EquipmentRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/clinics/$id': typeof ClinicsIdRoute
  '/shade/': typeof ShadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/designers': typeof DesignersRoute
  '/equipment': typeof EquipmentRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/clinics/$id': typeof ClinicsIdRoute
  '/shade': typeof ShadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/designers': typeof DesignersRoute
  '/equipment': typeof EquipmentRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/clinics/$id': typeof ClinicsIdRoute
  '/shade/': typeof ShadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/designers'
    | '/equipment'
    | '/portfolio'
    | '/services'
    | '/clinics/$id'
    | '/shade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/designers'
    | '/equipment'
    | '/portfolio'
    | '/services'
    | '/clinics/$id'
    | '/shade'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/designers'
    | '/equipment'
    | '/portfolio'
    | '/services'
    | '/clinics/$id'
    | '/shade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DesignersRoute: typeof DesignersRoute
  EquipmentRoute: typeof EquipmentRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  ClinicsIdRoute: typeof ClinicsIdRoute
  ShadeIndexRoute: typeof ShadeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers': {
      id: '/designers'
      path: '/designers'
      fullPath: '/designers'
      preLoaderRoute: typeof DesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shade/': {
      id: '/shade/'
      path: '/shade'
      fullPath: '/shade/'
      preLoaderRoute: typeof ShadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$id': {
      id: '/clinics/$id'
      path: '/clinics/$id'
      fullPath: '/clinics/$id'
      preLoaderRoute: typeof ClinicsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DesignersRoute: DesignersRoute,
  EquipmentRoute: EquipmentRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  ClinicsIdRoute: ClinicsIdRoute,
  ShadeIndexRoute: ShadeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
